name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  builds:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node jobs
        uses: actions/setup-node@v3
        with:
          node-version: '20.9'

      - name: Install dependency
        run: npm install

      - name: Run test
        run: npm run test
